environment_type: CartPole # {CartPole, TowersOfHanoi, Gambler}
environment_params:
  n_timesteps: 300
  L: 0.5
  m_p: 0.1
  m_c: 1.0
  g: 9.8
  F: 10.0
  theta_max: 0.21
  x_min: -2.4
  x_max: 2.4
  timestep_delta: 0.02
  buckets: (3,3,6,6)
actor_type: Actor
actor_params:
  discount: 0.7
  start_learning_rate: 1.0
  end_learning_rate: 0.1
  learning_rate_decay: 0.05
  start_epsilon: 1.0
  end_epsilon: 0.1
  epsilon_decay: 0.05
  trace_decay: 0.6
critic_type: TableCritic # {TableCritic, NetworkCritic}
critic_params:
  discount: 0.7
  start_learning_rate: 1.0
  end_learning_rate: 0.1
  learning_rate_decay: 0.05
  trace_decay: 0.6 # Only used by TableCritic
fit:
  n_episodes: 300